### PR TITLE
VG-3641, adds support for varargs to python pipeline step.

### PR DESCRIPTION
**Pull request by jdeolive**
Uses inspect module to verify that function declares a varargs argument.

### CODE REVIEW

**Comment by jdeolive** [comment]
This one is paired with https://github.com/voyagersearch/voyager-server/pull/23.

**Comment by jdeolive** [comment]
@newfoundgeo can you look this one over.

**Comment by newfoundgeo** [comment]
Looks good!

**Comment by samvoyager** [comment]
Merge it ... I'm really keen to test this one!

**Comment by ShaneRing** [comment]
Easy killer

**Pull request merged**
